project:
  type: website

website:
  title: "How to deal with darkness"
  site-url: https://tscnlab.github.io/ZaunerEtAl_JBiolRhythms_2025/
  repo-url: https://github.com/tscnlab/ZaunerEtAl_JBiolRhythms_2025
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: "Supplemental Material S1"
      - text: "License"
        href: license.qmd
    right:
      - icon: github
        href: https://github.com/tscnlab/ZaunerEtAl_JBiolRhythms_2025
        aria-label: Quarto GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

date: last-modified

language:
  title-block-published: "Last modified:"
